### ISSUE TITLE
Chyba u stenozáznamů z psp (api)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#103]
Cituji z podpory:

Zalogoval jsem se
Na stránce https://www.hlidacstatu.cz/data/Index/stenozaznamy-psp jsem kliknul na technické detaily a pak na Pokud jste zalogováni, můžete použít i tento odkaz: https://www.hlidacstatu.cz/api/v2/dump/dataset.stenozaznamy-psp
 
A ukázalo mi to „{"errors":{"date":["The date field is required."]},"type":https://tools.ietf.org/html/rfc7231#section-6.5.1,"title":"One or more validation errors occurred.","status":400,"traceId":"00-2d80eaaec2909b44acbdef79401359ce-2579aaa50c3f1547-00"}
„
 
Můžete poradit, kde dělám chybu?

**Comment by michalblaha** [comment]
fixnuto
