### ISSUE TITLE
Zařazení subjektu v rámci K-indexu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#107]
https://www.hlidacstatu.cz/kindex/zebricek/Statni_fondy

**Státní pozemkový úřad** (https://www.hlidacstatu.cz/subjekt/01312774) je mezi státními fondy - na žádost samotného úřadu prosím přeřadit z tohoto porovnání do 

https://www.hlidacstatu.cz/kindex/zebricek/Organizacni_slozky_statu

(via https://hlidacstatu.freshdesk.com/a/tickets/2723)

**Comment by michalblaha** [comment]
Mezi státními fondy je evidovám v RPP. Pokud to chce změnit, musí  změnit toto zařazení v RPP (my odtud čerpáme).

https://www.hlidacstatu.cz/subjekt/DalsiInformace/01312774
