### ISSUE TITLE
Data z nemocnic (update/přetextování)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#111]
Dotaz z podpory zda ještě aktualizujeme "kapacity nemocnic"
https://www.hlidacstatu.cz/kapacitanemocnic

Buď **zaktualizovat** (protože tam není aktuální stav) **nebo změnit text**, že už k datům nemáme přístup a proto jsou údaje neaktuální.

via freshdesk #2755

**Comment by suchoss** [comment]
Je tu i problém s odkazem: `/KapacitaNemocnicData/last`, který vrací 500, protože nemáme data.


Otázka je, jestli to nějak aktualizovat (nejen kvůli covidu)? Nebo jestli tyhle endpointy úplně zazdít. Pokud bude možné získávat data z nemocnic, tak bych byl raději pro variantu a) :)
