### ISSUE TITLE
Bug v API 

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#112]
via freshdesk (citace)

Zjistili jsme, že existují smlouvy, které lze vyhledat přes Váš web, ale v datech dostávaných přes API nejsou.
Například smlouva:
ISRS_ID_Smlouva = 16339783, ISRS_ID_Verze = 17591527
Detail: https://www.hlidacstatu.cz/Detail/17591527
nebo
ISRS_ID_Smlouva = 16326967, ISRS_ID_Verze = 17576619
Detail: https://www.hlidacstatu.cz/Detail/17576619
 
Smlouvy uvedených ID nejsou v DUMPech, které se získávají přes https://www.hlidacstatu.cz/api/v2/dumps.
 
Děkuji za pomoc

**Comment by suchoss** [comment]
Fixnul jsem jednu chybku v dumpech (přesměrování na staré apiV1), ale tenhle problém neopravím. Nevím, co ty dumpy vytváří. Problém nejspíš bude, že je soubor historicky vytvořen (dřív, než jsme zjistili, že existuje smlouva) a neaktualizuje se. Chtělo by to přegenerovat. @michalblaha poradíš?

**Comment by michalblaha** [comment]
Ve full dumpech je, není v denních dumpech

**Comment by michalblaha** [comment]
Upraven cas, kdy se dump generuje
