### ISSUE TITLE
Volební speciál - oprava adresy úřadu v našeptávači

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#113]
MČ Praha 12 je nově přestěhovaná (viz https://www.praha12.cz/vsechny-odbory-umc-praha-12-se-presunuly-do-nove-radnice/d-84435)

V našeptavači v https://volby.hlidacstatu.cz/?utm_source=hlidacstatu&utm_medium=header&utm_campaign=volby2021#/cr-cr máme starou adresu úřadu: Městská část Praha 12
Písková 830/25
143 00 Praha 4 - Modřany 

Radnice je ale nyní **přestěhovaná** na tuto správnou adresu: Městská část Praha 12
Generála Šišky 2375/6
143 00 Praha 4 - Modřany

**Comment by suchoss** [comment]
opraveno
