### ISSUE TITLE
Volby + mojeID - chyba u autocomplete?

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#120]
Cituju zprávu, kterou jsme dostali na podporu (freshdesk #2779):

Zdá se mi, že jsem nalezl bug v integraci mezi mojeID a Vaší aplikací pro generování žádosti o voličský průkaz.
Na screenshotu z mojeID je vidět, že mám trvalý pobyt v Praze 9, Veltruská 599/20: 
![image](https://user-images.githubusercontent.com/59918383/133285395-1f1fda4c-b929-4063-9f49-6ac9e9aeb27b.png)

Současně vím, že můj obecní úřad se nachází na adrese Sokolovská 14/324, 180 49 Praha 9 - fyzicky jsem tam byl pro OP.

V aplikaci na vašem webu po nahrátí dat z MojeID však vidím městský úřad Prahy 18 - viz 
![image](https://user-images.githubusercontent.com/59918383/133285474-71c237a5-0d9b-443e-b4b5-8e07e34c2758.png)

**Comment by suchoss** [comment]
Má nějaké divné psč. Správně by to (podle googlu) mělo být:
Sokolovská 14/324, 190 00 Praha 9-Vysočany

**Comment by suchoss** [comment]
Tak je chyba v uživateli. Všiml jsem si, že tenhle úřad máme, ale Veltruská 599/20 není Praha 18 - Letňany, ale Praha 9 - Prosek. 
![image](https://user-images.githubusercontent.com/39336141/133375478-de6559d5-27ae-4538-96db-0b79474135ef.png)
