### ISSUE TITLE
Nefunkční link u rizik na profilu úřadu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#124]
Profil: https://www.hlidacstatu.cz/subjekt/00094943
A ten nefunkční link je zde:
![image](https://user-images.githubusercontent.com/59918383/133971893-2a373d8d-7898-47d5-bfd7-1a39575f8316.png)

Vypadá takto: https://www.hlidacstatu.cz/subjekt/ico%3A00094943+AND+(+hint.smlouvaULimitu%3A%3E0+)+AND+datumUzavreni%3A%5B2020-01-01+TO+2021-01-01%7D
Hláška pak takto: 
![image](https://user-images.githubusercontent.com/59918383/133971962-1cec8cd8-3f9f-4deb-ab86-6fb3fa99ead3.png)

**Comment by michalblaha** [comment]
fixnuto do dnesniho releasu
