### ISSUE TITLE
JSON  z jednání zastupitelstev

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#126]
via freshdesk #2806

Dobrý den,
Po zalogování jsem klikl na tento odkaz : https://www.hlidacstatu.cz/data/TechnickeInfo/stenozaznamy-psp
A výsledkem bylo stažení JSON souboru,který obsahoval
[{"id":"1998_10_01477","lastUpdate":"2020-10-08T22:16:16.0442747Z"},{"id":"1998_10_01203","lastUpdate":"2020-10-08T22:16:17.2731478Z"},{"id":"1998_10_01536","lastUpdate":"2020-10-08T22:16:21.2780128Z"},{"id":"1998_10_01409","lastUpdate":"2020-10-08T22:16:21.2810158Z"},{"id":"1998_10_01374","lastUpdate":"2020-10-08T22:16:21.5692025Z"},{"id":"1998_10_01781","lastUpdate":"2020-10-08T22:16:22.7950736Z"},{"id":"1998_10_01649","lastUpdate":"2020-10-08T22:16:24.5533242Z"},{"id":"1998_10_01487","lastUpdate":"2020-10-08T22:16:25.0016429Z"},{"id":"1998_10_01829","lastUpdate":"2020-10-08T22:16:25.1817713Z"},{"id":"1998_10_01586","lastUpdate":"2020-10-08T22:16:26.0954214Z"},{"id":"1998_10_01756","lastUpdate":"2020-10-08T22:16:28.0127837Z"},{"id":"1998_10_01973","lastUpdate":"2020-10-08T22:16:28.5381571Z"},{"id":"1998_10_01798","lastUpdate":"2020-10-08T22:16:37.1642906Z"},{"id":"1998_10_02167","lastUpdate":"2020-10-08T22:16:38.2761028Z"},{"id":"1998_10_02029","lastUpdate":"2020-10-08T22:16:43.0955075Z"},{"id":"1998_10_02048","lastUpdate":"2020-10-08T22:16:43.2185952Z"},{"id":"1998_10_02179","lastUpdate":"2020-10-08T22:16:45.1829921Z"},{"id":"1998_10_00764","lastUpdate":"2020-10-08T22:15:48.6057654Z"},{"id":"1998_10_00821","lastUpdate":"2020-10-08T22:15:49.9136952Z"},{
 
A ne kýžené texty

**Comment by suchoss** [comment]
Pán nejspíše myslel tenhle odkaz https://www.hlidacstatu.cz/api/v2/dump/dataset.stenozaznamy-psp

Je pravda, že tam jsou pouze ID. Nejsem si jistý, že to ale fungovalo jinak. @michalblaha jaká by měla být funkčnost tohohle?

**Comment by michalblaha** [comment]
Přesně taková. Sumo vrací je od záznamů, záznamy musí poté stáhnout přes id
