### ISSUE TITLE
Chyba ve výpočtu "rizika" na profilu firmy/úřadu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#127]
Prevděpodobně máme chybu v riziku.

Příklad Moravská zemská knihovna - na profilu v oddílu Sledovaná rizika a linku na Koncentrace smluvních partnerů - https://www.hlidacstatu.cz/HledatSmlouvy?Q=ico%3A00094943+AND+(+hint.smlouvaULimitu%3A%3E0+)+AND+datumUzavreni%3A%5B2020-01-01+TO+2021-01-01%7D
vychází firma Digis, přestože v K-indexu v těchto parametrech je někde v půlce ne-li na konci - viz detail K-indexu https://www.hlidacstatu.cz/kindex/detail/00094943.

Kde se v těch rizicích tahle firma vzala, navíc s jedinou smlouvou jen za 2,2 mil.?

**Comment by suchoss** [comment]
Koukám, že u knihovny
[https://www.hlidacstatu.cz/Subjekt/00094943](https://www.hlidacstatu.cz/Subjekt/00094943
)
je
<img width="692" alt="image" src="https://github.com/HlidacStatu/Hlidac-Statu/assets/39336141/d1fbe98d-5702-4527-adfa-2a2a7a66ea72">
ale v odkaze je nejspíš chybně omezení na chyby zásadní
<img width="773" alt="image" src="https://github.com/HlidacStatu/Hlidac-Statu/assets/39336141/74e9264c-5784-4b2d-84b6-0f94dd3b9d8e">

Tady jsem přišel na to, že generujeme špatný odkaz - v **Apps\Webs\Web\Views\Subjekt\_rizikoPart.cshtml:123**:
`<a href="/HledatSmlouvy?Q=@query">` se vyskytuje proměnná query, která je vyplněná pro předchozí část `@if (statistics.PocetSmluvSeZasadnimNedostatkem > 0)`

A ten odkaz by měl vést ideálně na KIndex někam sem (ideálně rozkliknutý)
<img width="1263" alt="image" src="https://github.com/HlidacStatu/Hlidac-Statu/assets/39336141/ff405029-5f09-42d2-a9d7-3eee84f7aaf2">
