### ISSUE TITLE
Výsledky vyhledávání

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#134]
Občas se stane, že do hlavního vyhledávacího okna někdo napíše svoje plné jméno a hledá.
Bohužel se stává, že není nijak označeno, které z vyhledaných výsledků jsou přesné a které jsou díky fulltextu jen podobné.
Stane se tak, že firma s IČO a názvem Jméno Příjmění nevyhledá jen záznam o firmě, ale i o x insolvencích, veřejných zakázkách a smlouvách, které s touto firmou nemají v reálu nic společného (jen se tam vyskytuje část jména apod.).

Lze někde nad vyhledanými výsledky, které obsahují jen část jména firmy, vložit červenou větičku, že jde jen o podobnost a ne přesný výsledek?

Sem tam to bývá stížnost na podpoře.

**Comment by lenka-crypto** [comment]
Návrh na úpravu výsledku vyhledávání v případě, že vyhledávaný výraz není vložen do závorek:
![image](https://user-images.githubusercontent.com/59918383/148201488-f6e95e83-b738-4364-addc-6b2216aedfbf.png)

**Comment by suchoss** [comment]
Michal už nastavil
