### ISSUE TITLE
Dataset z VeKlep

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#139]
Via freshdesk #2866 
Pán si stěžoval na limit nad 200 záznamů při stahování, doporučena cesta přes api dump a stahování podle id. To už byl spokojen ale pokračuje takto:

"Další otázka: bylo by možné nějak opravit ty stovky souborů, které mají místo plaintextu hlášku
"Požadavek byl zablokován" (
https://www.hlidacstatu.cz/data/Hledat/veklep?Q=Po%C5%BEadavek+byl+zablokov%C3%A1n
říká že jich je 296, což jsou patrně unikátní záznamy - příloh s touto chybou vidím několikrát víc)? Chápu že odok.cz je temperamentní, a že se zásadně neobtěžuje posílat chybové kódy HTTP, nicméně myslím že ta chyba je rozeznatelná, a pravidelným opakováním by se dalo stáhnout víc..."

**Comment by suchoss** [comment]
Vypadá to fixnuté
