### ISSUE TITLE
Zobrazení sponzorů pro konkrétní politickou stranu

### ISSUE THREAD

**Issue by Eliska12** [HlidacStatu/Hlidac-Statu#14]
Ahoj,

v Hlídači politických stran https://www.hlidacstatu.cz/ucty je u transparentních účtů jednotlivých stran vždy odkaz: **Zobrazit sponzorující osoby a firmy strany XY.**
- Tento odkaz vždy odkáže na úvodní stránku Sponzoři https://www.hlidacstatu.cz/sponzori - nikoli na sponzory konkrétní politické strany - Takže na sponzory té konkrétní politické strany se dostaneme až díky dalšímu kliknutí - viz obrázek se sponzory Pirátů.

![sponzori pirati odkazy](https://user-images.githubusercontent.com/57462675/69152243-5a29e780-0adc-11ea-8b4b-031004b2d337.png)
![sponzori pirati odkazy 1](https://user-images.githubusercontent.com/57462675/69152242-59915100-0adc-11ea-8f1c-0e6dc68eff11.png)

**Comment by suchoss** [comment]
Sponzoring byl předělán
