### ISSUE TITLE
Report - složení psp čr

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#151]
Aktuální poslance evidujeme v reportu natvrdo podle nameid. 
Do budoucna zajistit podle neukončeného eventu "poslanec", aby byl report aktuální vždy po updatu eventu (politické funkce) osoby.

FYI: Momentálně máme report **Poslanci zvolení do parlamentu v 2017**  https://www.hlidacstatu.cz/Report/16

**Comment by suchoss** [comment]
Tohle je už podle eventů. Poslanci tam ještě nejsou přidaní nejspíš proto, že TI je ještě nepřidalo. Updatoval jsem seznam nováčků. @lenka-crypto - zavřeš tohle issue ve chvíli, kdy přibudou eventy na poslancích?

**Comment by suchoss** [comment]
Nastaveny eventy :)
