### ISSUE TITLE
nastavení Hlídání - chybný placeholder

### ISSUE THREAD

**Issue by Natali1888** [HlidacStatu/Hlidac-Statu#153]
Špatně se ukazuje ta věc v nastavení hlídání u subjektů - to co se má vyplnit v závorkách je chybně, viz obrázek
![Snímek obrazovky 2021-12-02 v 12 30 18](https://user-images.githubusercontent.com/84903728/144414151-746042b7-ec5f-4f65-8243-b43f4e40381e.png)

**Comment by suchoss** [comment]
Bylo fixnuto
