### ISSUE TITLE
Politický sponzoring - detailní zobrazení není detailní

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#161]
Na profilu osoby (status sponzor) jsou zobrazeny v případě více darů v náhledu vždy maximálně **tři dary** a možnost 
**ZOBRAZIT VŠECH XX DARŮ POLITICKÝM STRANÁM**
Po rozkliknutí je ale vidět jen souhrn po jednotlivých letech = ne detail jednotlivých darů s uvedením zda je dar finanční nebo bezúplatné plnění (tak to bývalo, ne?).

Příklad aktuálního zobrazení na profilu osoby:
![image](https://user-images.githubusercontent.com/59918383/149321033-0b0337d2-9611-4aec-b77e-dcbfe74ea9a4.png)
a po rozkliknutí detailního zobrazení:
![image](https://user-images.githubusercontent.com/59918383/149321154-a3e3a8c6-f331-46c0-a1eb-5849d9627255.png)

**Comment by lenka-crypto** [comment]
související issues: 190 a 218

**Comment by suchoss** [comment]
Takhle to nebylo. Má smysl to rozepisovat na jednotlivé dary? U některých lidí to může být hromada položek po 100 Kč...

**Comment by lenka-crypto** [comment]
Asi to smysl nemá, ale je důležité, abychom nezobrazovali **nulové dary** a pokud uvedeme počet darů, tak by ten počet měl po rozkliknutí detailu sedět.

**Comment by suchoss** [comment]
Máš nameid, kde to můžu zkontrolovat?

**Comment by suchoss** [comment]
Když například vezmu toto (https://www.hlidacstatu.cz/subjekt/sponzoring/03797775), tak nemůžu ten nulový smazat, protože tak je to ve zdrojových datech. Není to nefinanční dar. Nevím co to je.

**Comment by suchoss** [comment]
fixnuto
