### ISSUE TITLE
Hlídač státních webů

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#168]
Opravit staré url a doplnit další k hlídání

citace z helpdesku:
"Databáze lékáren již nějaký ten pátek  běží na jiném odkazu než uvádíte. Nově to má APIčko, i mapku s GPS.
https://www.hlidacstatu.cz/statniweby/info/257?h=655FD3D326D538667AEE4B8E5A641C31
https://prehledy.sukl.cz/prehledy.html#/lekarny
https://prehledy.sukl.cz/  "
 

Souvisejícící issues s hlídačem státních webů: 
https://github.com/HlidacStatu/Hlidac-Statu/issues/47
https://github.com/HlidacStatu/Hlidac-Statu/issues/157
https://github.com/HlidacStatu/Hlidac-Statu/issues/158

**Comment by lenka-crypto** [comment]
Doplňuji další via support:

"Mezi weby, kterým sledujete dostupnost, je uveden https://crab.uzsvm.cz/
 Tento web již není využívaný. Produkční verze CRAB je od 1. 1. 2020 dostupná na adrese https://ecrab.cz/. Další informace viz https://www.uzsvm.cz/crab. "

**Comment by michalblaha** [comment]
> Opravit staré url a doplnit další k hlídání
> 
> citace z helpdesku: "Databáze lékáren již nějaký ten pátek běží na jiném odkazu než uvádíte. Nově to má APIčko, i mapku s GPS. https://www.hlidacstatu.cz/statniweby/info/257?h=655FD3D326D538667AEE4B8E5A641C31 https://prehledy.sukl.cz/prehledy.html#/lekarny https://prehledy.sukl.cz/ "
> 
> Souvisejícící issues s hlídačem státních webů: #47 #157 #158

Fixed

**Comment by michalblaha** [comment]
vše opraveno/doplněno
