### ISSUE TITLE
Dataset API chyby

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#17]
1) dotaz na strukturu API (https://www.hlidacstatu.cz/Api/v1/Datasets/vyjadreni-politiku) mi vrací jiný JSON, než je v dokumentaci
2) dotaz na data (https://www.hlidacstatu.cz/Api/v1/DatasetSearch/vyjadreni-politiku?q=osobaid:marketa-adamova) pro jednotlivé stránky (page=x) vrací někdy sloupec pocetSlov, jindy pocetslov.

**Comment by suchoss** [comment]
@michalblaha Problém bude někde už při importování dat, protože takhle je to uloženo v ES:
```
get /data_vyjadreni-politiku/_search?size=1000
{
  "query":{
    "term": {
      "osobaid.keyword": {
        "value": "marketa-adamova"
      }
    }
  }
}
```

**Comment by suchoss** [comment]
@michalblaha přijde mi, že je to v pořádku. V kódu vidím všude `pocetSlov`

**Comment by suchoss** [comment]
api 1 už je obsolete
