### ISSUE TITLE
Nove statni weby ke sledovani

### ISSUE THREAD

**Issue by datastory** [HlidacStatu/Hlidac-Statu#170]
Zdravím, navrhuju přidat:

nssoud.cz
nalus.usoud.cz
sbirkapp.gov.cz
red.financnisprava.cz
sponzorpristup.agentura-cas.cz
kriminalita.policie.cz
vyhledavac.cak.cz
nkcr.cz

**Comment by michalblaha** [comment]
nastaveno, monitorováno.
