### ISSUE TITLE
Nesedí počet podřízených organizací u zobrazovaného subjektu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#176]
Město Český Těšín - IČO  00297437
https://www.hlidacstatu.cz/Subjekt/00297437

"Řídí [17 podřízených organizací.](https://www.hlidacstatu.cz/subjekt/Vazby/00297437)"

Cituji info interní auditorky města:

Tento údaj neodpovídá skutečnosti, některé z nich již dávno zanikly.
Jedná se o tyto organizace:
 
Základní škola Český Těšín Slezská 1740 okres Karviná
Základní škola a Mateřská škola Český Těšín Ostravská 1710 okres Karviná
Základní škola a Mateřská škola Český Těšín Masarykovy sady 104 okres Karviná
Mateřská škola Český Těšín Hrabinská 51, příspěvková organizace
Sociální služby Český Těšín, příspěvková organizace

**Comment by suchoss** [comment]
Opravit vazby tak, aby nezobrazovaly zaniklý subjekt

**Comment by suchoss** [comment]
No, to bude oříšek - aktuálně nemáme informaci o datu zániku, kterou pro správné zobrazení potřebujeme. Budu muset mrknout do zdrojových dat, jestli tam ta informace je, abychom ji dokázali použít

**Comment by suchoss** [comment]
Datum zániku nedostáváme od Merku, ačkoliv ho na stránkách mají. Michal kontaktuje lidi z Merku a zjistí, jestli nám ho tam přidají

**Comment by lenka-crypto** [comment]
Díky za informaci, předám. Bylo by opravdu mnohem lepší, mít aktuální data...

**Comment by suchoss** [comment]
Opraveno. Data nahrána, zautomatizováno a releasnuto.
