### ISSUE TITLE
Databáze VZ

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#177]
V databázi je vidět poslední změna u VZ z 1.4.2022 a velice pravděpodobně nemáme podchycené všechny zdroje. Např. https://www.vhodne-uverejneni.cz/. 
Tam jsem mrkla namátkou na Vsetínskou nemocnici (ičo:26871068) - u nás ve VZ poslední změna 12/2020, na zmíněném webu poslední zveřejnění dnes (jen za 2022 sedmá VZ).

see health checks: 
![image](https://user-images.githubusercontent.com/59918383/162453416-df251108-c3e7-44da-b1b5-8141e92b8233.png)
 a nebo úvod v db:
![image](https://user-images.githubusercontent.com/59918383/162453556-a539faf7-861d-43d2-9117-83337887fe2d.png)

**Comment by suchoss** [comment]
Všechny zdroje VZ zatím nemáme.
Kontroloval jsem to a načítá se to denně.
Co se týká toho posledního obrázku - ty nízké počty jsou způsobené tím, že většinou chybí uvedené kódy CPV u veřejných zakázek a tak je nedokážeme zařadit

**Comment by suchoss** [comment]
Většina chyb by měla být opravena
