### ISSUE TITLE
Kategorizace smluv - návrh na úpravy kategorií

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#178]
111 Aktuálně máme:
**Právní a realitní služby** (hlavní kategorie)
Nájemní smlouvy
Právní služby
Pronájem pozemků
Realitní služby

_Návrh na změnu:
**Právní a realitní služby**  (hlavní kategorie)
Právní služby (poradenství, konzultace...)
Realitní služby (poradenství, konzultace...)
Nákup/prodej, nájem/pronájem nemovitostí (bytové i nebytové prostory, pozemky, garáže...)_

222 Aktuálně máme:
**Sociální služby** (hlavní kategorie)
Knihovny, archivy, muzea a jiné
Rekreační, kulturní akce
Sociální péče
Vzdělávání a školení
Zdravotní péče

**Věda, výzkum a vývoj** (hlavní kategorie)

_Návrh na změnu:
**Věda, výzkum a vzdělávání** (hlavní kategorie)
Věda, výzkum, inovace (výzkumné nebo inovační projekty)
Školení a kurzy (pro veřejnost, pro odborníky)_

**Comment by suchoss** [comment]
Ty realitní mám připravené, ale nechápu tu 222 část. Co s čím sloučit a co na co rozdělit? Chápu že má vzniknout nová top level kategorie **věda, výzkum a vývoj** ale nevím, co přijde odstranit ze sociálních služeba a jak rozdělit klíčová slova pro tu vědu...

**Comment by suchoss** [comment]
Ještě je potřeba přesunout všechny smlouvy co obsahují:
```
[NiceDisplayName("Nájemní smlouvy")]
legal_najem = 11503,
[NiceDisplayName("Pronájem pozemků")]
legal_pozemky = 11504,
```
přesunout sem: `legal_nemovitosti = 11505`

**Comment by suchoss** [comment]
A @lenka-crypto - potřebuju, až budeš mít čas, abys upravila klíčová slova u několika (cca 10 - 15?) z těchhle smluv:
https://www.hlidacstatu.cz/hledat?q=smlouv%C4%9B+o+spolupr%C3%A1ci+a+poskytnut%C3%AD+podpory+mal%C3%A9ho

a zatřídila to do nově vzniklé kategorie 
```
[NiceDisplayName("Smlouvy o spolupráci")]
dary_spoluprace = 12001,
```

A až budeš mít zatříděno, tak mi dát sem vědět, abych mohl ještě reklasifikovat zbytek
