### ISSUE TITLE
Anti-robot nefunguje

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#18]
mám problémy s přihlašováním do Hlídače státu. Přihlašovací údaje mám uložené v password manageru (https://1password.com/) a když dám vyplnit přihlašovací formulář a odešlu jej, zobrazí se Stránka pro roboty.

Předpokládám, že důvod tohoto chování je, že password manager vyplňuje i skrytý input "email2". Bylo by možné formulář přizpůsobit tak, aby jej správci hesel dokázali korektně vyplnit?

Prohlizec: FIrefox

**Comment by suchoss** [comment]
Měli bychom někam přidat návod, že je potřeba odmazat "email2" z password managera (funguje pro LastPass):
![image](https://user-images.githubusercontent.com/39336141/128358804-6e9d3167-fd69-4536-926b-8641bf2de6b1.png)
![image](https://user-images.githubusercontent.com/39336141/128359090-883a7e66-ed17-4396-8200-ae55cc5b9e91.png)
![image](https://user-images.githubusercontent.com/39336141/128359343-0a7f299f-2100-432b-a7a7-d7e845f6d6a7.png)

@lenka-crypto určitě ocení tenhle návod, kam pak může odkazovat
@Natali1888 Dokážeš k obrázkům dodělat šipky?

První obrázek šipka k té propisce v červeném kolečku (vpravo nahoře)
Druhý obrázek šipka k tomu zašedivělému klíči na utahování matek (vlevo dole - ta druhá levá)
Třetí obrázek šipka k tomu křížku na zašedivělém pozadí u pole email2

**Comment by lenka-crypto** [comment]
Ten email2 s písmenkem "k" - to se v last passu takhle vyplnilo samo nebo to máš jako příklad?

**Comment by suchoss** [comment]
Jednou jsem to takhle zadal (na zkoušku) a od té doby se to takhle vyplňuje. Je to jako příklad. Ale prakticky jde o to, že prostě ten email2 musí být prázdný. Tam se nesmí nic vyplňovat.

Takže kdyby někomu nefungoval lastpass autocomplete, tak to jde takhle opravit.

1password nemám, tak tam nedokážu poradit.

**Comment by lenka-crypto** [comment]
Většina lidí, co měli teď po migraci Hlídače problém: "pomoc! nejsem robot!", už se přihlásila...  Po tom, co jsem jim řekla, ať si na první přihlášení vypnou našeptávač správce hesel..

**Comment by suchoss** [comment]
Jo, protože mají třeba zakliknuto "Zapamatuj si mě". Ale když se budou přihlašovat znovu, tak se jim to může zase stát. Tohle by mohlo pomoct potom, kdyby se museli po nějaké době opět přihlašovat.

**Comment by lenka-crypto** [comment]
Tak já napíšu návod s obrázkama+šipkama jako stránku (na wp) a link na ní by byl na Hlídači umístěný někde tady: https://www.hlidacstatu.cz/Identity/Account/Register - může být?

**Comment by suchoss** [comment]
Myslím, že jo :)

**Comment by radimk** [comment]
Mám stejný problém jako @michalblaha: Firefox + 1Password a jsem označen za robota. 
FWIW tady jsou komentáře tvůrců 1Password - https://support.1password.com/compatible-website-design/ https://1password.community/discussion/117501/as-a-web-developer-how-can-i-disable-1password-filling-for-a-specific-field - ale bojím se, že přidat `autocomplete="off"` k email2 možná nebude stačit.

**Comment by suchoss** [comment]
@radimk Můžete se podívat, jestli v pokročilém nastavení pro 1Password není vyplněno nějaké pole navíc?

S parametry `autocomplete="xxx"` jsem si nějakou dobu hrál s menší/větší úspěšností, ale problém to kompletně neřeší. Každý password manager si to řeší po svém.

**Comment by radimk** [comment]
1Password mi zadne pokročilé nastavení nenabízí. Nic, kde bych viděl nějake "email2" nebo něco podobného nemají.

**Comment by suchoss** [comment]
Přidali jsme alternativu - přihlášení přes google a apple.
