### ISSUE TITLE
Hlídač webů - chyba

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#180]
via freshdesk - 
"eIdentita změnila 28.11.2021 svůj název na identita občana.
Změnila se také doména z eIdentita.cz na Identitaobcana.cz"
Hlídáme toto: https://www.hlidacstatu.cz/statniweby/info/116?h=465A27162B843DD21B81928A6970FD73

Další neuzavřený issues ohledně hlídače webů: #47 #157 #158

**Comment by suchoss** [comment]
@lenka-crypto  @michalblaha V tomhle případě nechápu, co je záměr hlídat.

https://nia.eidentita.cz/IPSTS.SMS/Login
a
https://www.identitaobcana.cz/Home
mi přijdou jako dvě rozdílné věci a to co teď sledujeme (nia) je stále funkční a identitaobcana.cz na ni pořád odkazuje.

**Comment by suchoss** [comment]
hotovo
