### ISSUE TITLE
chyba v reportu hejtmanů

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#187]
https://www.hlidacstatu.cz/Report/18

Pravděpodobně je report sestavený podle názvu rolí "hejtman", ale tímto nám chybí kraj Hlavní město Praha, protože Hřib je "primátor".

Prosím, doplnit do reportu nameid: zdenek-hrib

**Comment by suchoss** [comment]
Mám pocit, že už jsme na to téma kdysi vedli diskusi. Nebylo by lepší přidat Hřibovi roli Hejtman? co myslíš @michalblaha ?

**Comment by michalblaha** [comment]
a nenazveme ji hetman/primator ?

On je proste primator

**Comment by suchoss** [comment]
No já myslel, že role primátor by mu zůstala, ale zároveň bychom přidali roli hejtman. Protože ve skutečnosti plní funkci 
hejtmana
a
primátora
