### ISSUE TITLE
Skuteční majitelé - proklik z profilu firmy

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#189]
Např.  tento subjekt: https://www.hlidacstatu.cz/subjekt/49618491

U seznamu skutečných majitelů je u jediného majitele/osoby link. Po rozkliknutí jména osoby https://www.hlidacstatu.cz/osoba/irena-cejzlarova, ale stránka hází chybu. Nejspíš proto, že osoba je POUZE jednatel (nemá IČO, není politický sponzor, není politik, není vysoký státní úředník... a má status "nepolitická osoba").

Návrh: 
a) odstranit odkaz od jména osoby nebo
b) proklik navést na nějakou unifikovanou stránku s hláškou, "osoba nemá žádné další zjištěné vazby"

**Comment by scippio** [comment]
Mně to teď funguje.
