### ISSUE TITLE
Vyškrtnuté dotace de minimis - nezobrazovat

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#197]
Zajistit aktuálnost údajů nějakou častější aktualizací, protože se může stát, že některé dotace nakonec nejsou vyplaceny/smlouvy zrušeny/nepodepsány.

Jeden příklad - opravit:
https://www.hlidacstatu.cz/data/Detail/de-minimis/1000593549
Tato dotace prý nikdy nebyla vyplacena. Píšou, že " podpora de minimis ke zrušené záruce byla z registru vymazána již 7.4.2022" a že "uvedená smlouva se nepodepsala".

**Comment by suchoss** [comment]
Upravil jsem template datasetu, aby se zrušené dotace (StavKod == 4 ) nezobrazovali. Zároveň spouštím update dotací, ale koukám, že endpoind vrací jen 10 000 záznamů. tak doufám, že se to updatne
