### ISSUE TITLE
https://www.hlidacstatu.cz/report/7 

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#20]
-> Hodnota uzavřených smluv v Kč po měsících -> Srpen 2019 je tam šíleně vysoké číslo asi nějaká anomálie.

**Comment by suchoss** [comment]
@michalblaha Srpen 2019 už je spravenej. Teď se to přesunulo do května 21... Asi chyba někde v grafu. Mrknu na to

**Comment by suchoss** [comment]
Tak to dělá hlavně tahle smlouva, která je zneplatněná:
https://www.hlidacstatu.cz/Detail/16173943

Ale taky do toho přispívají i další, třeba tahle (pravděpodobná) duplicita:
https://www.hlidacstatu.cz/Detail/16249491
https://www.hlidacstatu.cz/Detail/16221603

@michalblaha můžeš zkontrolovat, jak jsme se dnes bavili na callu, že nám funguje zneplatňování smluv?

A případně jak je to potom s promítnutím těch smluv do statistik. A kdyby s tím byly větší problémy, tak přepočítat ten poslední kindex. 

Dík
