### ISSUE TITLE
chybná identifikace dodatku smlouvy

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#200]
dodatek bez hodnoty: https://www.hlidacstatu.cz/Detail/20829655 se špatnou chybovou hláškou

"související" propojená s hodnotou: https://www.hlidacstatu.cz/Detail/8803695

**Comment by michalblaha** [comment]
Opraveno, počítáme i s odkazem na ID smlouvy (nikoliv pouze na ID verze, jak by melo byt spravne)
