### ISSUE TITLE
Vyjádření politiků na sociálních sítích

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#206]
Je potřeba zajistit, aby se do vyjádření nestahovala reklamní sdělení (twitter).

viz třeba bývalá ministryně - https://www.hlidacstatu.cz/data/Hledat/vyjadreni-politiku?q=(+OsobaId%3Aalena-schillerova+)+
![image](https://user-images.githubusercontent.com/59918383/183382656-6f08d5de-62a2-4a73-9c02-04fe9ca6bf92.png)

**Comment by lenka-crypto** [comment]
Chybí nejnovější tweety některých osob. Např. Mračková-Vildumetzová, přestože tweetuje a v eventu máme korektní nick, od roku 2020 se nic nestahuje:
https://www.hlidacstatu.cz/data/Hledat/vyjadreni-politiku?q=(+OsobaId%3Ajana-mrackova-vildumetzova+)+

**Comment by michalblaha** [comment]
Mrackova fixnuta https://www.hlidacstatu.cz/data/Hledat/vyjadreni-politiku?order=datum%20desc&q=osobaid%3Ajana-mrackova-vildumetzova
