### ISSUE TITLE
Sledování webů (chyba v url)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#208]
https://www.hlidacstatu.cz/StatniWeby/Info/385

Pravděpodobně šlo v minulosti o sledování někdejší jazykové mutace, ale aktuálně už je homepage bez "druhého" /cz.
Opravit na sledování url https://www.frydekmistek.cz/

**Comment by lenka-crypto** [comment]
Další chyba ve sledovaném url.
máme ještě http - https://www.hlidacstatu.cz/StatniWeby/Info/106 
ale už je to https - https://info.mojedatovaschranka.cz/info/cs/

**Comment by suchoss** [comment]
Hotovo a hotovo :)
