### ISSUE TITLE
Veřejné zakázky - chyba exportu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#214]
V případě vyhledaného odoru VZ se při kliknutí na export exportují všechny VZ a ne jen ten vyhledaný obor.
Např. IT, HW, SW - https://www.hlidacstatu.cz/verejnezakazky/hledat?q=*&oblast=IT&order=1
Kliknutím na export dojde k exportu VŠECH veřejných zakázek (tzn i z jiných oborů).

**Comment by suchoss** [comment]
Myslím, že by mělo stačit změnit někde tady v `HlidacStatu.Web.Controllers.VerejneZakazkyController.Hledat`, aby `&oblast` nebyl samostatný parametr, ale aby byl součástí `q`, takže výsledná query by v tomto případě byla `hledat?q=oblast:IT&order=1`

**Comment by suchoss** [comment]
Tohle vytváří hledání, ale nenastaví querystring:
``` c#
public static QueryContainer GetSimpleQuery(VerejnaZakazkaSearchData searchdata)
{
    var query = searchdata.Q?.Trim();
    string modifiedQ = query; // Search.Tools.FixInvalidQuery(query, queryShorcuts, queryOperators) ?? "";
    //check invalid query ( tag: missing value)
    
    if (searchdata.Zahajeny)
        modifiedQ = Query.ModifyQueryAND(modifiedQ, "zahajeny:1");
    
    if (!string.IsNullOrWhiteSpace(searchdata.Oblast))
    {
        var oblValue = NormalizeOblastValue(searchdata.Oblast);
        if (!string.IsNullOrEmpty(oblValue))
            modifiedQ = Query.ModifyQueryAND(modifiedQ, "oblast:" + oblValue);
    }

    var qc = SimpleQueryCreator.GetSimpleQuery<VerejnaZakazka>(modifiedQ, Rules);

    return qc;
}
```
