### ISSUE TITLE
Politický sponzoring, formát osob - uvozovky

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#219]
ODS 2021, fyzické osoby v uvozovkách

seznam zde: https://www.hlidacstatu.cz/Sponzori/SponzoriStrany/ODS

příklad: https://www.hlidacstatu.cz/Osoba/Index/ales-opatrny-2
zdroj: https://zpravy.udhpsh.cz/export/vfz2021-ods-penizefo.json

**Comment by suchoss** [comment]
Hejhou, je to fixnuté. Bylo to jen 32 "nových" osob. Taky jsem fixnul kód, takže tenhle typ chyby by se už neměl stávat
