### ISSUE TITLE
chyba vyhledávání v sekci "Sponzoři"

### ISSUE THREAD

**Issue by scippio** [HlidacStatu/Hlidac-Statu#221]
Zkoušel jsem zadat dvě osoby u Sponzorů. Dynamické vyhledávání mi samo napovědělo správně, ale po kliknutí na Hledat se zobrazila chyba.
Například při vyhledávání osoby: "Ivan Bartoš".

Také mi to v podstatě okamžitě začne hlásit:
![image](https://user-images.githubusercontent.com/672903/202440199-8d4ce2f2-6a20-4800-9d3c-7d83f56e54eb.png)

**Comment by suchoss** [comment]
Pravděpodobně k tomu došlo ve chvíli, kdy jsme pustili nefunkční release do produkce. Dnes se už neprojevuje.
