### ISSUE TITLE
Slovenské IČO, chyba propojení

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#232]
U jedné smlouvy došlo publikující stranou k chybě u identifikace smluvní strany. Smluvní strana je slovenská, ale IČO bylo zapsáno do obvyklé kolonky v RS. Bohužel je IČO SK subjektu totožné s IČO českého subjektu (který nemá žádnou smlouvu v RS) a došlo tak u nás k propojení "slovenské" smlouvy s českým subjektem.

Viz: https://www.hlidacstatu.cz/hledat?q=ico%3A14011883
chyba je u dodavatele v této smlouvě: https://www.hlidacstatu.cz/Detail/4872824
subjekt IČO 14011883 s touto smlouvou nená nic společného.

**Comment by suchoss** [comment]
Popravdě vůbec netuším, co s tím. 
IČO je opravdu SROčka 

Netuším, jestli IČO podnikatele je správně. Každopádně v tuto chvíli nemáme IČO v takové struktuře, abychom to nastavili. Nenapadá mě jednodušší řešení než rozsáhlý refactoring celé aplikace (IČO je prorostlé napříč celým hlídačem)

**Comment by michalblaha** [comment]
fixed
