### ISSUE TITLE
Chyba v zobrazení počtu smluv

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#241]
Subjekt má jednu jedinou smlouvu v roce 2017 viz https://www.hlidacstatu.cz/HledatSmlouvy?Q=oblast:stav%20AND%20ico:12898694%20AND%20podepsano:[2017-01-01%20TO%202017-12-31]

V zobrazení na profilu je ale uvedeno 21 smluv v oboru stavebnictví viz  https://www.hlidacstatu.cz/subjekt/RegistrSmluv/12898694%C2%A0
![image](https://user-images.githubusercontent.com/59918383/227920861-a556ca90-ee7b-4206-8ac0-5a8c6fa8dd5f.png)

**Comment by michalblaha** [comment]
opraveno v cache
