### ISSUE TITLE
nový autocomplete - nenachazí položky, divne razeni

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#242]
kdyz hledas "cez", neukaze ČEZ, a.s.

kdyz zadáš píšes dál až k "cez a.", ČEZ ukáže.
Po napsání "cez a.s" opět zmizí.

CEZ by tak jako tak melo ukazovat prvni, protoze je to nejkratsi jmeno, nejvice podobne...

**Comment by suchoss** [comment]
fixnuto v 4d2e1baf58c41f4a5a80c157d9f98f507a43aa97
