### ISSUE TITLE
počet podřízených organizací měst

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#246]
Např. město Český Těšín.
https://www.hlidacstatu.cz/Subjekt/Vazby/00297437?aktualnost=Aktualni
My uvádíme, že řídí [17 podřízených organizací.] Což dle pracovníka úřadu již několik let neplatí viz korektní aktuální zaslaný seznam:

Město má zřízeno pouze 10 příspěvkových organizací a jednu a.s.
 
1.Teplo Těšín a.s.
akcionář v Teplo Těšín a.s. (od 10.02.1998)
2.Centrum sociálních služeb Český Těšín, příspěvková organizace
Zřizovatel příspěvkové organizace v Centrum sociálních služeb Český Těšín, příspěvková organizace (od 23.12.2009)
3.Správa účelových zařízení, příspěvková organizace
zakladatel OPS v Správa účelových zařízení, příspěvková organizace (od 18.07.2007)
4.Kulturní a společenské středisko "Střelnice"
Zřizovatel příspěvkové organizace v Kulturní a společenské středisko "Střelnice" (od 23.12.2009)
5.Masarykova základní škola a mateřská škola Český Těšín
Zřizovatel příspěvkové organizace v Masarykova základní škola a mateřská škola Český Těšín (od 23.12.2009)
6.Základní škola a mateřská škola Český Těšín Hrabina, příspěvková organizace
Zřizovatel příspěvkové organizace v Základní škola a mateřská škola Český Těšín Hrabina, příspěvková organizace (od 01.01.2012)
7.Základní škola s polským jazykem vyučovacím a Mateřská škola s polským jazykem vyučovacím Český Těšín Havlíčkova 13 okres Karviná
Zřizovatel příspěvkové organizace v Základní škola s polským jazykem vyučovacím a Mateřská škola s polským jazykem vyučovacím Český Těšín Havlíčkova 13 okres Karviná (od 23.12.2009)
8.Základní škola a mateřská škola Český Těšín Pod Zvonek, příspěvková organizace
Zřizovatel příspěvkové organizace v Základní škola a mateřská škola Český Těšín Pod Zvonek, příspěvková organizace (od 23.12.2009)
9.Středisko volného času Amos, Český Těšín, příspěvková organizace
zakladatel obecně prospěšné společnosti v Středisko volného času Amos, Český Těšín, příspěvková organizace (od 11.11.2006)
10.Základní škola a mateřská škola Český Těšín Kontešinec, příspěvková organizace
Zřizovatel příspěvkové organizace v Základní škola a mateřská škola Český Těšín Kontešinec, příspěvková organizace (od 01.01.2012)
11.Městská knihovna Český Těšín
Zřizovatel příspěvkové organizace v Městská knihovna Český Těšín (od 23.12.2009)

**Comment by lenka-crypto** [comment]
Už jsme to začali řešit a nedořešili: https://github.com/HlidacStatu/Hlidac-Statu/issues/176

**Comment by suchoss** [comment]
Duplicita #176 

řešme to v jednom issue
