### ISSUE TITLE
Skuteční majitelé - zobrazení celých jmen

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#249]
Skutečný majitel má dvě křestní jména a příjmení, ale my zobrazujeme pouze začátek = dvě křestní jména.
https://www.hlidacstatu.cz/subjekt/17902223
zde info o skutečném majiteli (celé jméno) - https://esm.justice.cz/ias/issm/rejstrik-$sm?ico=17902223&jenPlatne=PLATNE&polozek=50&typHledani=STARTS_WITH&typHledaniSpolku=ALL

Zajistit nápravu = uvedení kompletního jména.

**Comment by suchoss** [comment]
U této firmy konkrétně je fixnuto. Teď jsem spustil komplet load pro všechny, který by to měl pofixovat...
