### ISSUE TITLE
Veřejné zakázky

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#256]
Nejze rozkliknout detail veřejné zakázky (stránka nenalezena). Chyba registrována uživateli cca od poloviny 7/2023.

VZ lze vyhledávat, filtrovat atd., ale po kliknutí na detail jakékoliv VZ se zabrazí:
![image](https://github.com/HlidacStatu/Hlidac-Statu/assets/59918383/4c82e044-8aa0-4506-bb31-6df2034ad974)

**Comment by suchoss** [comment]
Odstraněn starý alias z VZ (netuším, jak se tam dostal)
