### ISSUE TITLE
Odkazy na portály zadavatele - VZ na profilu obcí/měst

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#265]
Obec provedla nedávno změnu obecního webu a nově je odkaz na zakázky jiný. Je potřeba link na profilu obce u nás aktualizovat v případě, že nedojde ke změně automaticky.

Obec na Hlídači: https://www.hlidacstatu.cz/subjekt/00241806
Tamní linky: https://www.hlidacstatu.cz/subjekt/VerejneZakazky/00241806

Platný odkaz, jak nám ho zaslala obec: https://www.velke-prilepy.cz/obecni-urad-2/verejne-zakazky/aktivni-vyberova-rizeni/

**Comment by suchoss** [comment]
Tak vestnik verejnych zakazek je vypnuty a misto nej existuje https://vvz.nipez.cz/

Budu muset pro to udělat nový scraper, který dokáže stáhnout data z těchto stránek.

**Comment by michalblaha** [comment]
Podle odpovedneho cloveka z MMR budou open data pro profily zadavatelu k dispozici od ledna 2024 s novym vestnikem
