### ISSUE TITLE
admin - Blazor: zmena UI hlasky "could not connect… Reload…"

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#269]
Zmenit default hlasku s disablovanim cele obrazovky na uzky pruh (dole ci nahore, to je jedno) s tlacitkem/linkem "reload" bez zmeny focus ci prekryti zbytku stranky neklikaci vrstvou. 
Podobne jako hledani na Hlidaci.

**Comment by suchoss** [comment]
hotovo
