### ISSUE TITLE
Databáze - Ministři - oprava v textu

### ISSUE THREAD

**Issue by Eliska12** [HlidacStatu/Hlidac-Statu#27]
Prosím o opravu překlepu v textu zde https://www.hlidacstatu.cz/data/Index/ministri

Text:
Zde je seznam ministrů českých vlád od 1992. Zdrojem dat je seznam ministrů vlád ČR z Wikipedie , který jsme _**vyčistily**_ -> vyčistili

**Comment by suchoss** [comment]
@michalblaha Tyhle gramatické opravy budeš muset udělat ty, já nemam přístup k tomu datasetu.

**Comment by suchoss** [comment]
Fixed manually.
