### ISSUE TITLE
Odkaz na K-index jednotlivých úřadů

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#270]
Odkaz hlásí chybu
zde příklad: https://www.hlidacstatu.cz/kindex/detail/00248266
(15.9.2023)

**Comment by suchoss** [comment]
Myslím, že to bude chybou u zahraničních IČ. 

Jednu jsem fixnul a našel jsem další:

ICO: "Europejskie Ugrupowanie Współpracy Terytorialnej Novum z o.o."

Je potřeba rozšířit metodu `NormalizeIco` v parse tools

@michalblaha mrkneš na to? Dík

**Comment by suchoss** [comment]
Michal fixnul zbytek
