### ISSUE TITLE
osoby navázané na úřady

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#273]
Návrh na doplnění seznamu osob ke konkrétním úřadům.

Např. Ministerstvo vnitra a na jeho profilu i odkaz na osoby:
- angažované politicky (ministři - navrchu ten současný a chronologicky pak až k nejstaršímu evidovanému)
- angažované úřednicky (veřejná správa exekutivní = náměstci ministra, náměstci pro řízení sekcí, ředitelé odborů, tajemníci... tady už by asi stačili jen ti s neukončeným eventem navrchu, podle abecedy a po nějaké mezeře ti ex)

Hodilo by se to i pro kontrolu, zda máme aktuální k tomu kterému ministerstvu (pilotně asi jen ministerstva... ?, to by se snadněji zkontrolovalo, pak by se mohlo postupovat dál třeba po krajích)

**Comment by suchoss** [comment]
Ministerstva hotova
