### ISSUE TITLE
Monitoring státních webů (přechody na nové domény!)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#279]
Poměrně značné množství státních webů přešlo, nebo bude v dohledné době přecházet na nové domény (dia, gov etc..)
Bude proto potřeba změnit hlídané url.

Upozornění uživatele z ÚPV (citace): 
V minulosti jste pro hlídání dostupnosti služeb Úřadu průmyslového vlastnictví používali adresu https://isdv.upv.gov.cz/webapp/glob.frm. 
Tento link se již delší dobu nepoužívá, nicméně byl stále funkční až do minulého týdne, kdy došlo k přechodu služeb ÚPV pod doménu isdv.upv.gov.cz (místo isdv.upv.cz) a pro původní link již nebylo nadefinované přesměrování, jelikož link je spojen s již nepoužívaným databázovým schématem. Podle https://www.hlidacstatu.cz/statniweby/info/176?h=undefined to vypadá, že původní link stále využíváte a naše služby tak vypadají jako nedostupné. Mohli byste si prosím aktualizovat odkaz na jeho novou podobu, tzn. https://isdv.upv.gov.cz/webapp/!resdb.glob.frm, aby se dostupnost našich služeb zobrazovala správně?

**Comment by michalblaha** [comment]
zmeneno na https://isdv.upv.gov.cz/webapp/!resdb.glob.frm
