### ISSUE TITLE
Social banner

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#289]
Infografika z textu (body) a obrázku (img) nefunguje ve správě účtu jako obvykle. 
(např. infografika na program jednání vlády)
Funguje to pouze pokud se nepoužijí html tagy, což je chyba, protože chceme zachovat dosavadní formát (tučné písmo, barva textu, odstavce..).

**Comment by suchoss** [comment]
Chyba byla jinde - Radware nám to rozbil, ale screenshoter nefunguje vždy úplně nejlíp - neumí dobře styly
