### ISSUE TITLE
skuteční majitelé - rozdílné zobrazení na dvou místech

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#297]
Zde příklad: 

Přímo **na profilu firmy** viz https://www.hlidacstatu.cz/subjekt/02212871 je vidět, že existuje jen jeden aktuální majitel. A že to druhé jméno patří BÝVALÉMU=VYMAZANÉMU majiteli.

Ovšem když se na profilové stránce firmy sjede dolu, do **sekce Subjekt v dalších databázích** a rozklikne se link "Skuteční majitelé", pak jsou **jak vymazaný tak i aktuální majitel uvedeni v jednom řádku**,což bez jakékoliv pochybnosti budí dojem, že jde o dva aktuální spolumajitele = chyba: https://www.hlidacstatu.cz/data/Hledat/skutecni-majitele?q=(+ico.keyword%3A02212871+)

**Comment by suchoss** [comment]
Fixnul jsem to v zobrazení datasetu
