### ISSUE TITLE
Prověřit data do watchdogů

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#298]
viz citace ze zprávy uživatele (13.11.)
"
všiml jsem si, že Hlídač státu už neeviduje nově přihlášené insolvence: https://www.hlidacstatu.cz/Insolvence#:~:text=Podrobn%C3%A9%20informace%20o%20insolvenc%C3%ADch%20jsou,a%20osob%20s%20n%C3%ADm%20obchoduj%C3%ADc%C3%ADm.

Zároveň mám pocit, že dostávám mnohem méně upozornění u nastavených hlídačů, které monitorují změny v evidenci skutečných majitelů u konkrétních hlídaných fyzických osob. Jen pro ilustraci, mám na mysli tuto evidenci.https://www.hlidacstatu.cz/data/Hledat/skutecni-majitele?q=ren%C3%A1ta+and+kellnerov%C3%A1
"

**Comment by michalblaha** [comment]
fixed
