### ISSUE TITLE
Chyba v identifikaci subjektu (IČO/název)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#299]
Uživatel si všiml chyby. Pod IČO 00000205 by měl být subjekt Vojenské lesy a statky ČR, s.p. , ale my zobrazujeme název Arca Investments, a.s., v reštrukturalizácii. Oprava nutná!
https://www.hlidacstatu.cz/Subjekt/00000205

**Comment by michalblaha** [comment]
v db opraveno
@suchoss , oprav to v autocomplete...

**Comment by suchoss** [comment]
@michalblaha Opět rozbité - něco nám to přepisuje
