### ISSUE TITLE
Nastavení filtrů - weby státu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#301]
menu Dotace a další - následující linky mají sice rozdílné URL, ale zobrazují stejnou stránku. 
Je potřeba sprovoznit filtry podle názvů kategorií, jak asi dříve fungovaly...

[Služby nejdůležitějších úřadů](https://www.hlidacstatu.cz/StatniWeby/ustredni)
[Rejstříky, registry a důležité databáze](https://www.hlidacstatu.cz/StatniWeby/registr)
[Důležité služby a weby veřejné správy](https://www.hlidacstatu.cz/StatniWeby/sluzba)
[Městské weby](https://www.hlidacstatu.cz/StatniWeby/mesta)
[Krajské weby](https://www.hlidacstatu.cz/StatniWeby/kraj)

**Comment by suchoss** [comment]
Fixnuto #38e399f8aa6ef05e54346d1c762f7f5a4b53f7cd
