### ISSUE TITLE
ocr - kontrola některých formátů smluv

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#303]
Zkontrolovat ocr... 
např. příloha smlouvy v txt, zveřejněná 1.11., dosud se zdá být nepřečtená ocr
(nebyla zatříděná. klasifikace až mnou) https://www.hlidacstatu.cz/Detail/26321243

další ale pdf. 5/2023
https://www.hlidacstatu.cz/Detail/24377165

**Comment by michalblaha** [comment]
fixed in fullocrminion:1.2.1
