### ISSUE TITLE
automatické zprávy při návrhu na reklasifikaci smluv

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#304]
Od večera 11. prosince přestaly chodit zprávy z webu na e-mail - ta třetí varianta z níže uvedených.

Při návrh na změnu klasifikace smlouvy chodí vždy tři zprávy:

1. na e-mail podpory, přímo od navrhovatele změny, s předmětem: Zprava z HlidacStatu.cz: classification
2. na e-maily týmu, z mailu podpory, s předmětem: Zprava z HlidacStatu.cz: Změna kategorie klasifikace  (obsahuje hodnoty slov dosavadního zatřídění + seznam vygenerovaných n-gramů, které nebyly použity)
3. na můj e-mail, z mailu podpory, s předmětem: Zprava z HlidacStatu.cz: classification (obsahuje navrhovanou klasifikaci a explain result s poměry)

**Comment by suchoss** [comment]
Našel jsem problém - klasifikátor. Dnes snad bude opravený, tak bych ho poté releasnul.
