### ISSUE TITLE
Označení z.ú. chybně jako Firma (spolu)vlastněná státem...

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#305]
Uvedený subjekt - z.ú. - má označení jako **Firma (spolu)vlastněná státem či samosprávou. Ústav.** 
Správně by měl mít popis **Soukromá firma. Ústav.**

Jde o subjekt: https://www.hlidacstatu.cz/Subjekt/06619550
Ten byl založen Nadací Č. Spořitelny, ta byla založena Č. Spořitelnou a ta je vlastněna Erste = v současné době žádná účast státu.

**Comment by michalblaha** [comment]
fixnuto opravou OVM
