### ISSUE TITLE
Revize aktualizace Skutečných majitelů

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#310]
Uživatel informoval o změně v evidenci skutečných majitelů, která u nás ale prozatím neproběhla.
Nutno zkontrolovat.

Příklad zde:
stav u nás (už neplatný) - https://www.hlidacstatu.cz/subjekt/01901613
aktuální záznam v evidenci - https://esm.justice.cz/ias/issm/rejstrik-$sm?ico=01901613&jenPlatne=PLATNE&polozek=50&typHledani=STARTS_WITH&typHledaniSpolku=ALL

**Comment by michalblaha** [comment]
fixed
