### ISSUE TITLE
změny url - Hlídání webů státu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#311]
ARES - hlídáme zde: https://www.hlidacstatu.cz/StatniWeby/Info/108
ale aktuální url je už toto: https://ares.gov.cz/ekonomicke-subjekty

U ministerstev jsou k aktuálnímu dni na gov.cz tyto, zatím... (viz https://www.hlidacstatu.cz/StatniWeby/Dalsi/ustredni):
https://mmr.gov.cz/cs/uvod
https://mzv.gov.cz/jnp/
https://www.mk.gov.cz/
(ke dni 5.1.24)

**Comment by michalblaha** [comment]
Ares opraveny.
u ministerstev testujeme starou domenu i novou, kvuli funkcnimu presmerovani ze stare na novou
