### ISSUE TITLE
rozbité IČO - identifikace subjektu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#316]
Uživatel na profilu své organizace zjistil chybu.

Profil org. https://www.hlidacstatu.cz/Subjekt/00849081 

Uživatel nalezl chybu v oddílu **Statistika dodavatelů (smluvních partnerů) subjektu**
Na prvním místě je [Autoškola SINEX s.r.o.,se sídlem Čadca, Kukučínova 960](https://www.hlidacstatu.cz/subjekt/00000278) ale s tímto subjektem (Autoškola SINEX s.r.o.,se sídlem Čadca, Kukučínova 960) podle našeho uživatele **nikdy neobchodovali** - proto nahlásil, že tu máme chybu.
Po rozkliknutí linku https://www.hlidacstatu.cz/subjekt/00000278 se zobrazí chybová hláška (viz obr.)
Doplňuju ale, že při kontrole podle ARESu tam toto IČO hlásí chybu "Hodnota musí být platný identifikátor IČO." = tzn. nebude chyba jen v názvu.
![image](https://github.com/HlidacStatu/Hlidac-Statu/assets/59918383/43395837-e2e0-4fef-9e81-b34211545403)

**Comment by lenka-crypto** [comment]
Podle hodnoty v přehledu dodavatelů subjetu jsem našla smlouvu na 77000,-, kde měl být dodavatel ta Autoškola, ale jako smluvní partner je v detailu smlouvy uveden subjekt, u kterého vkladatel zapomněl vložit IČO do metadat. viz https://www.hlidacstatu.cz/Detail/2182198

**Comment by suchoss** [comment]
IČO toho formedu je 13642481, 

co teď s tím @michalblaha ?
