### ISSUE TITLE
CZ x SK IČO záměna 

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#318]
SK smlouvy se chybně přiřadili k CZ subjektu - viz text níže

https://www.hlidacstatu.cz/Home/HledatFirmy?q=43987311
https://www.hlidacstatu.cz/subjekt/43987311

https://www.hlidacstatu.cz/hledat?q=43987311&qtl=8
https://www.hlidacstatu.cz/Subjekt/SK-43987311

Citace z dopisu uživatele:

"Je to pár let zpátky, kdy jsem upozorňovala na nepravdivé údaje na vašich stránkách týkajících se mého obchodního jména a **IČO 43987311, Ing. Barbora Toušková**. Domluvila jsem se tehdy ... a byla přislíbena náprava. ČÁSTEČNĚ K NÍ DOŠLO, ALE NĚCO SE OPĚT POKAZILO.
 Včera jsem náhodně kontrolovala informace o mé osobě na internetu a k mému nemalému údivu jsem zjistila, že u mého čísla IČO 43987311 opět funguje nesmyslný záznam  o 19 smlouvách, které jsem já nikdy neuzavřela, o finančním obratu nemluvě.
 Jedná se zřejmě o **slovenskou firmu PIPS SK s.r.o, která má dílem náhody na Slovensku stejné IČO 43987311**, jako já v ČR.
 Prosím tedy o uvedení informací dostupných na vašich webových stránkách do souladu se skutečností, včetně vymazání nepravdivých údajů o smlouvách v souvislosti s mou osobou, vymazání grafů apod."

**Comment by lenka-crypto** [comment]
Smlouvy slovenské firmy s IČO stejným jako je CZ jsme dokázali odstranit od české firmy, ale stále visí u české firmy slovenské VZ.
https://www.hlidacstatu.cz/subjekt/43987311 - to je CZ subjekt, který by neměl mít žádné smlouvy (to je už ok) a taky žádné VZ (to je ještě potřeba upravit).

**Comment by michalblaha** [comment]
opraveno, projevi se do 24 hod
