### ISSUE TITLE
Jednání zastupitelstev - nezpracovávají se

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#344]
viz příklad zde: https://www.hlidacstatu.cz/data/Hledat/zasedani-zastupitelstev?Q=ico%3A00279943&order=datum%20desc

**Comment by michalblaha** [comment]
Opraveno, uz se zpracovávají

dataset	celkem zaznamu	za Měsíc	posl.změna 
zasedani-zastupitelstev	4325	4181	10.07.24
