### ISSUE TITLE
API pro data ze sekce Sponzoři

### ISSUE THREAD

**Issue by ondrejpialek** [HlidacStatu/Hlidac-Statu#35]
Dobrý den,

měl bych zájem o strojově čitelná data, která máte na webu v sekci [Sponzoři](https://www.hlidacstatu.cz/sponzori).

Pokud byste prozatím měl třeba i dump surových dat, byl bych za ně moc vděčný.

Děkuji,
Ondřej.

**Comment by suchoss** [comment]
@ondrejpialek 

Dobrý den, konečně jsem se dostal k Vašemu požadavku. Endpoint je zde:
 `https://api.hlidacstatu.cz/api/v2/sponzoring/{ico politicke strany}`
