### ISSUE TITLE
Administrace účtu na HS ze strany uživatele

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#37]
V administraci účtu uživatele HS zařídit:
* deaktivace účtu
* změna/editace e-mailu uživatele (+nějaký ověřovací kód?)

Případně do té doby nějaké rozhraní, kde tohle můžeme jednoduše udělat my admini.

**Comment by suchoss** [comment]
![image](https://user-images.githubusercontent.com/39336141/134504866-261cbb16-0c32-46f3-8ae5-accfdd52f565.png)
