### ISSUE TITLE
PRI5 promazat robots.txt texty.hlidacstatu.cz

### ISSUE THREAD

**Issue by MartinKamin** [HlidacStatu/Hlidac-Statu#376]
Smazat 
`Sitemap: https://texty.hlidacstatu.cz/sitemap.xml
`
z robots.txt texty.hlidacstatu.cz

**Comment by michalblaha** [comment]
@MartinKamin 
robots.txt na disku nemame. Tzn. ze ho vytvari nejaky plugin, nejspise ten, co dela sitemaps…
