### ISSUE TITLE
Nepřesnosti - skuteční majitelé firem

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#384]
Chyba na profilu osoby dole, v oddílu Osoba v dalších databázích > Skuteční majitelé firem.

Příklad:
[Osoba](https://www.hlidacstatu.cz/osoba/ivana-tykac-1) 
Rozkliknutí níže uvedeného odkazu [Skuteční majitelé firem](https://www.hlidacstatu.cz/data/Hledat/skutecni-majitele?q=(+OsobaId%3Aivana-tykac-1+)+)
Zobrazuje také subjekty, kde osoba není majitelem.
A například [tato firma](https://www.hlidacstatu.cz/Subjekt/Index/24253774), kde osoba je majitelem, v uvedeném seznamu chybí.

Existuje několik dalších open issues na téma skut. majitelé, může souviset.

**Comment by suchoss** [comment]
@michalblaha `https://www.hlidacstatu.cz/data/Hledat/skutecni-majitele?Q=osobaid%3Aivana-tykac-1`

Tady to vyhledá i osoby, které neobsahují ani Ivana, ani Tykač. Např `https://www.hlidacstatu.cz/data/Detail/skutecni-majitele/10985964`

**Comment by suchoss** [comment]
`osobaid:` vyhledává ve výsledku přes IČO. A protože paní vlastní firmu, která vlastní firmu, tak ji zobrazujeme tady. 

A protože se hledá přes IČO a paní nemá přes IČO aktuální vazbu (není v dozorčí radě) na ELLESEINA, tak se nezobrazuje - `osobaid:` **nevyhledává podle jména a příjmení**
