### ISSUE TITLE
PRI3 https://www.hlidacstatu.cz/Report/5

### ISSUE THREAD

**Issue by MartinKamin** [HlidacStatu/Hlidac-Statu#386]
**Haprují nám miliardy**

![image](https://github.com/user-attachments/assets/c66340f2-2c07-4b65-92ff-29da1c34ff5e)

URL [https://www.hlidacstatu.cz/Report/5](https://www.hlidacstatu.cz/Report/5)

**Comment by suchoss** [comment]
Ne, nám ne:
Je potřeba se podívat na smlouvu:
https://www.hlidacstatu.cz/detail/26100451
a na zdroj:
https://smlouvy.gov.cz/smlouva/26100451

Nemáme jak zkontrolovat částky - to jsou data, která přebíráme od státu
