### ISSUE TITLE
PRI5: Pokročilé hledání (z profilu úřadu) má na konci rozsahu datumů složenou závorku a 

### ISSUE THREAD

**Issue by MartinKamin** [HlidacStatu/Hlidac-Statu#394]
Při vkládání dotazů s pomoci ENTER se na konci rozsahu datumů vloží složená závorka 
`}`
![image](https://github.com/user-attachments/assets/0d5f11d6-835b-4235-a5ad-9ebc00c259d4)

Dotaz se generuje odtud:
https://www.hlidacstatu.cz/subjekt/65349423

Je v části Registr smluv:
Vážné nedostatky za letošní rok jsme zjistili u jedné smlouvy. 

Dotaz je správné URL
 
[https://www.hlidacstatu.cz/hledatsmlouvy?q=ico%3A65349423+AND+chyby%3Avazne+AND+datumUzavreni%3A%5B2024-01-01+TO+2025-01-01%7D](
https://www.hlidacstatu.cz/hledatsmlouvy?q=ico%3A65349423+AND+chyby%3Avazne+AND+datumUzavreni%3A%5B2024-01-01+TO+2025-01-01%7D)

Ve výsledku ale ve vyhledávání vypadne takto:
![image](https://github.com/user-attachments/assets/9458b89f-3ce0-44a9-a97d-d2f6f6fc4628)

**Comment by suchoss** [comment]
@MartinKamin Co je na tom špatně? Interně používáme elasticsearch a ten používá Lucene. Hranatá závorka = inclusive, složená závorka = exclusive.
<img width="412" alt="image" src="https://github.com/user-attachments/assets/3339faf3-82f8-47c5-81a7-5bc4e9d6f8fd">
