### ISSUE TITLE
Přejmenování kategorie (vyhledávání osob)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#399]
Jde o vyhledávání osob - i ty, které nemají žádnou přímou i nepřímou vazbu na politiky (sponzoringem nebo obchodováním), zobrazujeme v této kategorii a s tímto popisem.

Přejmenovat kategorii a text níže doplnit i o variantu: přímá nepřímá obchodní vazba na stát.

(příklad na obrázku je [osoba](https://www.hlidacstatu.cz/Osoby/Hledat?Q=Hana%20Kyrianov%C3%A1&Page=1), která nemá žádnou politickou ani sponzorskou vazbu, pouze její firmy uzavřely obchod se státem via freshdesk # 17002)

![Snímek obrazovky 2024-09-09 094029](https://github.com/user-attachments/assets/2fdbcbde-32e9-4848-a74a-15340f8acf26)

**Comment by suchoss** [comment]
Potřebuju, abys mi napsala jak to tedy textově má být správně (Co kam za text). Nejsem zrovna ve stavu, kdy bych to dokázal vymýšlet :(

**Comment by lenka-crypto** [comment]
Asi bych doporučila na OSOBY, případně na OSOBY A JEJICH VAZBY, což by mělo pokrýt vše (bez toho, abychom upozorňovali na některé skupiny, které se mohou cítit dotčeny, pokud do některé nespadají.).
![365557999-2fdbcbde-32e9-4848-a74a-15340f8acf26](https://github.com/user-attachments/assets/ece20ea5-0548-4cfb-8459-e4bc5725defd)
