### ISSUE TITLE
Klasifikace smluv

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#401]
Nelze změnit/přidat obor. 

![signal-2024-09-16-145046_002](https://github.com/user-attachments/assets/943d19ee-a9f1-48b0-adcc-432ec57c4ecc)

**Comment by suchoss** [comment]
Je to opravené ručně - chyba se lokálně neprojevuje - opravil jsem spolu s tím kus kódu, který mi tu nefungoval.
