### ISSUE TITLE
Aktualizace statutu subjektu

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#402]
V hlídači evidujeme firmu s "v likvidaci" v názvu, ale od června (via VR) už zase normálně fungují. https://www.hlidacstatu.cz/subjekt/06841503
 VR: https://or.justice.cz/ias/ui/rejstrik-firma.vysledky?subjektId=1003712&typ=UPLNY

**Comment by suchoss** [comment]
Z Merku to máme špatně:

`cz-6841503,6841503,"Lodzie-Prejda s.r.o. ""v likvidaci""",1,2,20180207,,1,,112,2,120,50,4120,100.0,1,0,0,2,CZ0805,CZ080,cz`

**Comment by suchoss** [comment]
A koukám, poslední data z Merku máme 15.6. - Takže to tam být nemůže...
