### ISSUE TITLE
K-Index ukazuje přihlášenému uživateli "informace pro adminy"

### ISSUE THREAD

**Issue by MartinKamin** [HlidacStatu/Hlidac-Statu#406]
Ahoj K-index --- %SUBJ%

[https://www.hlidacstatu.cz/kindex/detail/00241881](https://www.hlidacstatu.cz/kindex/detail/00241881)
zobrazí tohle a **nejsem si jistý, zda je to chtěné** a zda se to nezobrzí běžnému uživateli, můžete to checknout? Děkuji

![image](https://github.com/user-attachments/assets/43c1e5f2-b549-49f9-b246-32f6297f89ea)

**Comment by suchoss** [comment]
Martine, můžeš to odzkoušet i Ty - podívej se na stránku jako nepřihlášený uživatel, nebo si vytvoř ještě jednoho uživatele se základními právy...
