### ISSUE TITLE
Nefunkční odkazy

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#408]
U valné většiny "dalších datasetů" =  https://www.hlidacstatu.cz/data/ máme ve žlutém boxu nefunkční odkazy.
vedou na platforma.hlidacstatu - to ale nefunguje - hází 404/401

_Pokud máte tip na zajímavý zdroj dat, **podělte se s ostatními**. Anebo se **koukněte na nápady ostatních**._ 
Oba tyto linky vedou na neexistující adresu: https://platforma.hlidacstatu.cz/t/datove-zdroje-vhodne-pro-zpracovani-tipy-a-napady/320

![image](https://github.com/user-attachments/assets/c0b97ec1-8c2b-4743-8206-1946476fc086)

**Comment by michalblaha** [comment]
je to opravene v repozitory, az dame release, bude to opravene i na serveru
