### ISSUE TITLE
Uveden důvod neuvedení hodnoty smlouvy

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#429]
Zajistit detekci matadat v položce 
**Cena neuvedena:**

V případě vyplnění důvodu a zároveň při prázdné položce metadat 
**Hodnota bez DPH:
Hodnota vč. DPH:**

zajistit to, aby se nevkládala naše poznámka o nedostatku
![image](https://github.com/user-attachments/assets/117b5c9b-0ee4-4274-9882-e0f035372b7b)
a tím také, aby se nepočítala do 1. parametru K-Indexu.

Příklad takové smlouvy: https://www.hlidacstatu.cz/Detail/30234264

**Comment by michalblaha** [comment]
fixed
