### ISSUE TITLE
HLÍDAČ STÁTNÍCH WEBŮ tipy na rozšíření 

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#47]
tip via freshdesk #1490 
https://opendata.mfcr.cz/ 

tip via freshdesk #1567
Doplnit monitoring pro https://www.epreskripce.cz/  (ne web ale službu, přes kterou elektronická preskripce probíhá. Software, přes který předepisují lékaři  zasílá při předpisu data do centrálního úložiště receptů, které tuším spravuje SÚKL, odtud informace o receptu pak zase přebírá lékárna vydávající léčivo. Tato služba má občas výpadky a doufal jsem, že by ta služba šla podobně pingovat jako jdou webové stránky."

dál  - postsignum.cz 
nebo  https://archi.gov.cz/

**Comment by suchoss** [comment]
@lenka-crypto Můžeš k tomu dát větší detail? Netuším co se chce s tím prvním.

Máš odkaz na tu službu, přes kterou preskripce probíhá? (1567)

Co s tím postsignum a archi.gov.cz

**Comment by lenka-crypto** [comment]
Nic bližšího ten lékař nepsal, ale myslím, že to bude někde tady: https://system.erecept.sukl.cz/suklweb/System/Account/Login

Služba postsignum je certifikace = elektronický podpis. Spravuje to Česká pošta. https://www.postsignum.cz/zakaznicky-portal/

https://archi.gov.cz/ je Architektura eGovernmentu ČR !!! Monitorovat asi https://archi.gov.cz/vyhledavani:changelog

**Comment by suchoss** [comment]
hotovo
