### ISSUE TITLE
Organizační struktury úřadů

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#57]
Buď je chyba u zdroje, nebo se něco stalo u nás, ale už není vidět to grafické propojení a není uveden počet služebních a pracovních míst - všude nuly. Zkontrolováno namátkou několik ministerstev. Zde link - příklad MF
https://www.hlidacstatu.cz/subjekt/OrganizacniStruktura/00006947

![image](https://user-images.githubusercontent.com/59918383/125079390-d6af7680-e0c3-11eb-845c-2f14b918d7d8.png)

**Comment by suchoss** [comment]
Problém je, že v nových opendatech (https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00007064%2F846439539) chybí počty pracovních míst.

**Comment by lenka-crypto** [comment]
Dokázali bychom u konkrétních org.str. uvést poznámku, že ve zdroji údaj chybí?

**Comment by suchoss** [comment]
To bych spíš odmáznul ta čísla, pokud informace chybí. Co myslíš?

**Comment by lenka-crypto** [comment]
Jasně, smazat. Pokud to nebude mít vliv na vykreslení toho pavouka, tak ok.
