### ISSUE TITLE
doplnění seznam českých poslanců Evropského parlamentu

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#6]
do seznamu politiku na Hlidači.

**Comment by suchoss** [comment]
Doplňuje Lenka ručně k eventům podle https://www.europarl.europa.eu/czechia/cs/va%C5%A1i-poslanci/dev%C3%A1t%C3%A9-volebn%C3%AD-obdob%C3%AD-2019-2024
