### ISSUE TITLE
Databáze Zasedání zastup. - chybí jmenný seznam

### ISSUE THREAD

**Issue by Natali1888** [HlidacStatu/Hlidac-Statu#66]
Prosím, v databázi Zasedání zastupitelstev opět chybí abecední seznam měst a krajů, díky kterému je možné snáze vyhledávat. Viz obrázek http://stagecore.hlidacstatu.cz/data/Index/zasedani-zastupitelstev

![Snímek obrazovky 2021-07-13 v 19 57 03](https://user-images.githubusercontent.com/84903728/125502059-e28f71b8-b414-4228-afaa-d1c16dbf1916.png)

**Comment by lenka-crypto** [comment]
Nefunguje dobře ani link z profilové stránky úřadu.
viz město Dobříš: https://www.hlidacstatu.cz/subjekt/00242098
link, na který se člověk dostane: https://www.hlidacstatu.cz/data/Hledat/zasedani-zastupitelstev?Q=00242098%3A00261891&order=datum%20desc

**Comment by lenka-crypto** [comment]
Dále chybí zpracovaný záznam https://www.youtube.com/watch?v=16q10yKtJeU&list=PLlOS5hlMJW7v2KKyhDnSLOe8l7Zybfokm&index=1
pro město Dobříš.
V seznamu zpracovaných není: https://www.hlidacstatu.cz/data/Hledat/zasedani-zastupitelstev?Q=ico%3a00242098&order=datum%20asc
