### ISSUE TITLE
NÁVRH: seznam polit. stran a hnutí

### ISSUE THREAD

**Issue by Natali1888** [HlidacStatu/Hlidac-Statu#68]
Asi mě nebudete mít rádi, ale nestálo by za tu v databázi http://stagecore.hlidacstatu.cz/data/Index/seznam-politickych-stran udělat jmenný seznam nejdůležitějších stran a hnutí? Alespoň těch, co mají třeba přes 3 % a pak dát jen "další"? Když už to máme v databázích vyjádření politiků, zasedání zastupitelstev atd...

**Comment by michalblaha** [comment]
> Stejně tak u databáze ministrů - udělat seznam ministerstev (těch tolik není), aby si každý mohl podle jednotlivého ministerstva najít, kdo a kdy tam byl ministrem

https://www.hlidacstatu.cz/Report/25
a
https://www.hlidacstatu.cz/Report/28

**Comment by suchoss** [comment]
myslím, že už máme
