### ISSUE TITLE
Vkládací banner K-index 

### ISSUE THREAD

**Issue by Natali1888** [HlidacStatu/Hlidac-Statu#72]
Chtely bychom s Lenkou vkladaci banner s K-indexem, aby si ho urady mohly přidat na svoje webovky

**Comment by suchoss** [comment]
Myslím, že už něco dělal Michal.

@michalblaha pokud je to vyřešený, tak prosím zavři tohle issue

**Comment by michalblaha** [comment]
Fixnuto, , fialove tlacitko na detailu K-Indexu

kod je `<script src='https://www.hlidacstatu.cz/widget/zbru2?width=500' type='text/javascript'></script> <div id='zbru2' style='width:500px' widget-page='/kindex/detail/**00297437**'></div> ` kde tucne je ICO subjektu
