### ISSUE TITLE
Chyba ve vedení statutárního města/magistrátu 

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#75]
via freshdesk 2654

bug - zobrazujeme souhrnné údaje za statutární město, kde ukazujete „starostu“ – Yvetu Tomkovou, která je ale starostkou jedné městské části. Statutární město má primátora a měl by tam tedy být zobrazen on. Celé statutární město by se pak mělo stávat z primátora a 4 starostů. https://www.hlidacstatu.cz/Subjekt/00081531

další info o členění a představitelích - cituju ze zprávy:

Větší města jako je např. Plzeň, ale i právě statutární město Ústí nad Labem se stávají z Magistrátu města a poté městských částí – tzv. městských obvodů. V Ústí nad Labem pak tedy máme následující strukturu:
 
Statutární město Ústí nad Labem
Magistrát města – primátor
                Úřad městského obvodu 1 – starosta
                Úřad městského obvodu 2 – starosta
                Úřad městského obvodu 3 – starosta
                Úřad městského obvodu 4 – starosta
 
Magistrát je hlavním představitelem a městským obvodům pak svěřuje určité agendy za pomoci statutu města.
 
Hlavním problémem tedy je, že mají společné IČO, ač vystupují odděleně (magistrát má primátora, zastupitelstvo a radu, a každý obvod má starostu, zastupitelstvo i radu).

Tady je k obvodům více informací.
https://www.usti-nad-labem.cz/cz/uredni-portal/sprava-mesta/urady-mestskych-obvodu/
 
Rozdělení identifikace by pak šlo udělat buď dle adresy datových schránek a nebo pomocí tzv. jedinečného identifikátoru OVM. Ten kvůli základních registrům apod., rozděluje magistrát i městské části na logické celky (tj. stejné IČO, ale odlišné OVM).
 
Pro ilustraci pak OVM úřadu městského obvodu Střekov: https://rpp-ais.egon.gov.cz/AISP/verejne/ovm-spuu/katalog-ovm/57551

**Comment by suchoss** [comment]
Už bylo asi nejspíš opraveno.
