### ISSUE TITLE
Chybná data v objektu skuteční majitelé

### ISSUE THREAD

**Issue by suchoss** [HlidacStatu/Hlidac-Statu#77]
https://www.hlidacstatu.cz/subjekt/29161215 

![image](https://user-images.githubusercontent.com/39336141/127653004-950fd555-d122-407c-b626-2829ccf9f776.png)

dostává se nám na stránku null hodnota. Ta je nejspíš uložena v https://github.com/HlidacStatu/Hlidac-Statu/blob/main/Web/Views/Subjekt/RightColumn.cshtml#L150 `@(skm["postaveni"].Value<string>())`.

**Comment by michalblaha** [comment]
tak je to ve zdrojovych datech
