### ISSUE TITLE
Vyhledávání - nefunkční operátor

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#78]
https://www.hlidacstatu.cz/napoveda

Nefunguje logický operátor **mínus**

Příklad třeba zde: Česká televize mínus reklama > https://www.hlidacstatu.cz/hledat?q=ico%3A00027383+-reklama

**Comment by suchoss** [comment]
Duplicate of #29

**Comment by michalblaha** [comment]
Opraveno v napovědě na NOT
