### ISSUE TITLE
Znovu rozšířit nastavení Hlídačů na profilové stránce osob/úřadů/firem

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#80]
Nově máme na profilu osoby/úřadu/firmy jen jednoho souhrnného Hlídače:
![image](https://user-images.githubusercontent.com/59918383/128051251-11a74151-21e7-42c6-b3a1-46881fec83bb.png)
 
Dříve šlo ale hlídat zvlášť několik agend viz 
![image](https://user-images.githubusercontent.com/59918383/128051334-9aedf245-7948-4476-a1d3-d9ae4ff0494d.png)

Co kdybychom nechali jednoho souhrnného Hlídače hned na titulce profilu, ale dali ještě jednoho Hlídače ke každé kategorii těch jednotlivých souhrnných statistik?
Jakože po rozkliknutí 
https://www.hlidacstatu.cz/Osoba/Funkce/jana-cernochova
https://www.hlidacstatu.cz/Osoba/Sponzoring/jana-cernochova
https://www.hlidacstatu.cz/Osoba/RegistrSmluv/jana-cernochova 
atd. atp.
by na konci/na začátku byl nastavený hlídač (ta oranžová věta s očkem), a to stejný i u firem a úřadů.

**Comment by lenka-crypto** [comment]
A pozor, nastavení Hlídačů třeba ve vyhledaných smlouvách atp. má jinou oranžovou barvu (bledší) než na profilu úřadu/osoby (sytá). Sjednotit, ať je to všude jednou barvou.

**Comment by suchoss** [comment]
Rozpracováno, nalezl jsem zde i bug.

**Comment by suchoss** [comment]
Tag bug je fixnutej. Na callu jsme si říkali, že nebudeme dávat hlídání jednotlivých podstránek, protože to trochu postrádá smysl a ne všude to umíme.
