### ISSUE TITLE
Error u "medailonku" vyhledaného IČO soukromé firmy

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#83]
https://www.hlidacstatu.cz/hledat?q=ico%3A+70985383

Zobrazený medailonek níže odkazuje na https://www.hlidacstatu.cz/subjekt/error

![image](https://user-images.githubusercontent.com/59918383/128181387-7f5461b4-f0c1-4a34-970d-68e8c9cc6a3b.png)

**Comment by suchoss** [comment]
Dotrasoval jsem to sem
Problém vzniká tady: https://github.com/HlidacStatu/Hlidac-Statu/blob/main/Web/Views/Home/Hledat.cshtml#L346
Kde `var splQ = HlidacStatu.Repositories.Searching.SplittingQuery.SplitQuery(Model.Query);` vrací špatně splitnuté `ico: 70985383` kvůli té mezeře

Tady je potom nejspíš jádro problému: https://github.com/HlidacStatu/Hlidac-Statu/blob/main/Repositories/Searching/SplittingQuery.cs#L233

```
tPart = tPart.Replace("(", " ( ").Replace(")", " ) ")
    .Replace(": (", ":(");//fix mezera za :
```

V tom replacnutí se replacuje pouze mezera za dvojtečkou následovaná `(`. Tady by to dle mě mělo být spíš takhle:
`.Replace(": (", ":(");`

**Comment by suchoss** [comment]
Důvod proč to jinde funguje je, že jinde před zavoláním
`SplittingQuery.SplitQuery(Model.Query);`
voláš ještě: 
`Tools.FixInvalidQuery(query,rules)`.
