### ISSUE TITLE
Profil úřadu --- graf+tabulka dodavatelů/odběratelů

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#85]
viz https://www.hlidacstatu.cz/subjekt/dodavatele/00254657

Pod tabulkou/grafem je znovu přepínátko na graf i tabulku. 
Spodní přepínátko zobrazuje data jen při kliknutí na tabulku, ale po kliknutí na graf se nic nezobrazí.
![image](https://user-images.githubusercontent.com/59918383/128229608-090be403-afc5-44dc-a04c-fe0f90b894a4.png)

**Comment by suchoss** [comment]
Problém je firma "v likvidaci". Je potřeba do JSONu escapovat znaky
