### ISSUE TITLE
profil osoby - dvoje různé vazby mají stejné url

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#89]
Příklad Milan Feranec - https://www.hlidacstatu.cz/osoba/milan-feranec

Obě url (viz obrázek 1) jsou stejná - vedou na VŠECHNY vazby - to je matoucí. Čekala bych, že podrobnosti budou vést na ty soukromé vazby a v tom druhém případě jen na ty státní. Pokud to nedokážeme odlišit jinak než v tom náhledu tří příkladů firem na profilu osoby, tak bych byla pro sloučení těch dvou oddílů do jednoho - viz třeba návrh obrázek 2.

![image](https://user-images.githubusercontent.com/59918383/128521886-0019ec4e-138b-4266-af06-b4df49df809a.png)
![image](https://user-images.githubusercontent.com/59918383/128521927-a99eca6b-cb75-4399-a43e-be56fb780126.png)

**Comment by michalblaha** [comment]
to je zatim schvalne.
