### ISSUE TITLE
Update CEO při změně CEO u úřadů

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Hlidac-Statu#90]
viz https://www.hlidacstatu.cz/subjekt/00240478, kde je P.Peckova namisto nove starostky.

**Comment by suchoss** [comment]
Asi úplně nechápu - 
![image](https://user-images.githubusercontent.com/39336141/131973339-b813071f-0659-417a-9b58-8519e53a6807.png)

**Comment by michalblaha** [comment]
uz fixnuto, omylem nezavreno
