### ISSUE TITLE
Stav mostů - není update už rok + bugs

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#94]
1.) Databáze nebyla updatovaná už rok.
2.) Defaultně je v mapě nastavený "Velmi špatný" a "Havarijní stav" - imho defaultně by mělo být vše.
3.) Nelze z nabídky stavů (2.) vyfiltrovat třeba stav "Bezvadný", který v nabídce byl (1.) 
![image](https://user-images.githubusercontent.com/59918383/128637238-78701c3b-ac64-4df8-8fac-0d40fa1f6453.png)
![image](https://user-images.githubusercontent.com/59918383/128637249-305ef47e-9071-4e4c-b6dd-676b2a0a95fc.png)

**Comment by michalblaha** [comment]
1) fixed
2) ne, takto je to spravne, jinak je tam bodu moc
3) fixed
