### ISSUE TITLE
https://www.hlidacstatu.cz/Report/21

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/Hlidac-Statu#98]
Prosím, zajistit do budoucna update podle neukončeného eventu a podle zaškrtnutýho CEO.
Současný report je natvrdo podle nameid.

K dnešnímu dni (9.8.2021) je sestava taková:
jan-hamacek
alena-schillerova
karel-havlicek-3
jakub-kulhanek-2
marie-benesova
richard-brabec
lubomir-metnar
miroslav-toman
jana-malacova
robert-plaga
klara-dostalova
lubomir-zaoralek
adam-vojtech-1

**Comment by michalblaha** [comment]
Pridat obdobu Firma.Zatrideni i pro lidi /ministri, vedeni uradu, starostove, …) @suchoss

**Comment by suchoss** [comment]
Done
